CREATE TABLE `re` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,  
  `ngay_bgl8` datetime DEFAULT NULL,
  `email_bg` varchar(255) DEFAULT NULL,
  `san_pham` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `sdt` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `thuc_thu` double DEFAULT NULL,
  `ht_thanhtoan` varchar(255) DEFAULT NULL,
  `giatritaikhoan` double DEFAULT NULL,
  `thoigianhoc` bigint(20) DEFAULT NULL,
  `nguoncts` varchar(255) DEFAULT NULL,
  `loaihocvien` varchar(255) DEFAULT NULL,
  `ngaytienve` datetime DEFAULT NULL,
  `loaitaikhoan` varchar(255) DEFAULT NULL,
  `khuyenmai` varchar(255) DEFAULT NULL,
  `contactid` varchar(255) DEFAULT NULL,
  `makhoahoc` varchar(255) DEFAULT NULL,
  `kenhcrm` varchar(255) DEFAULT NULL,
  `tvtscrm` varchar(255) DEFAULT NULL,
  `flowtheotvts` varchar(255) DEFAULT NULL,
  `kenhquidoi` varchar(255) DEFAULT NULL,
  `ngaydangky` datetime DEFAULT NULL,
  `xacnhantienve` varchar(255) DEFAULT NULL,
  `gc1` varchar(255) DEFAULT NULL,
  `gc2` varchar(255) DEFAULT NULL,
  `gc3` varchar(255) DEFAULT NULL,
  `spreadsheets_id` varchar(255) DEFAULT NULL,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
