CREATE TABLE `tic` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ho_ten` varchar(255) DEFAULT NULL,
  `sdt` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `trang_thai_cs` varchar(255) DEFAULT NULL,
  `trang_thai_goi` varchar(255) DEFAULT NULL,
  `level` varchar(255) DEFAULT NULL,
  `ngay_dk` DATETIME DEFAULT NULL,
  `kenh` varchar(255) DEFAULT NULL,
  `mau_qc` varchar(255) DEFAULT NULL,
  `tu_khoa` varchar(255) DEFAULT NULL,
  `ghi_chu` text,
  `ngay_bg_tvts` DATETIME DEFAULT NULL,
  `tvts` varchar(255) DEFAULT NULL,
  `nghiem_thu` varchar(255) DEFAULT NULL,
  `so_call` bigint(20) DEFAULT NULL,
  `noi_dung_call` text,
  `ngay_goi_gan_nhat` DATETIME DEFAULT NULL,
  `ngay_hen_goi_lai` DATETIME DEFAULT NULL,
  `kho` varchar(255) DEFAULT NULL,
  `ngay_bg_qttt` DATETIME DEFAULT NULL,
  `ngay_tic` varchar(255) DEFAULT NULL,
  `flow_nhan_bg` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `gc1` varchar(255) DEFAULT NULL,
  `gc2` varchar(255) DEFAULT NULL,
  `gc3` varchar(255) DEFAULT NULL,
  `spreadsheets_id` varchar(255) DEFAULT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
